### ISSUE TITLE
Python 2 Wheel

### ISSUE THREAD

**Issue by prologic** [rdegges/python-ipify#1]
Please build and publish Python 2.x wheels as well please :)

**Comment by rdegges** [comment]
Heyo! Hmm, I built the universal wheel since this distribution works on both python2 and python3 without changes, so I don't think I need to?

Correct me if I'm wrong though!

Here's what the PyPI page shows:

![screenshot 2015-05-07 10 17 18](https://cloud.githubusercontent.com/assets/90247/7521389/5ed6d0c2-f4a2-11e4-9f09-5790f3b4d79b.png)

**Comment by rdegges** [comment]
Closing for now, but please re-open if I'm not right!

**Comment by prologic** [comment]
Yeah I think you might be right. It was late at night and tbh I didn't try installing the wheel yet :) I just know of the ipify service and it's awesome! Now there's a library in Python and it's even more awesome :)

**Comment by rdegges** [comment]
Whew, awesome! Thanks for using the service ^^ It's been really fun writing something that so many people use.
